# Generated by Django 5.1.4 on 2025-01-29 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('cartao', 'Cartão'), ('pix', 'Pix')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('falha', 'Falha')], default='pendente', max_length=20)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
