# Generated by Django 5.1.4 on 2025-02-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('falha', 'Falha')], max_length=20),
        ),
    ]
