# Generated by Django 5.1.4 on 2025-02-11 22:28

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('categoria', models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('roupas', 'Roupas'), ('livros', 'Livros'), ('esportes', 'Esportes'), ('outros', 'Outros')], default='outros', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='products.produto')),
            ],
        ),
    ]
