# Generated by Django 5.1.4 on 2025-01-30 03:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
